# Generated by Django 6.0.8 on 2026-08-07 05:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud_accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CostRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("service", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=4, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("date", models.DateField()),
                ("region", models.CharField(blank=True, max_length=50, null=True)),
                ("is_synthetic", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cloud_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_records",
                        to="cloud_accounts.cloudaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["cloud_account", "date"],
                        name="cloud_accou_cloud_a_bfa393_idx",
                    ),
                    models.Index(
                        fields=["service"], name="cloud_accou_service_fa030c_idx"
                    ),
                ],
            },
        ),
    ]
