# Generated by Django 6.0.8 on 2026-08-19 11:37

import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud_accounts", "0002_costrecord"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cloudaccount",
            name="aws_access_key_id",
        ),
        migrations.RemoveField(
            model_name="cloudaccount",
            name="aws_secret_access_key",
        ),
        migrations.AddField(
            model_name="cloudaccount",
            name="external_id",
            field=models.CharField(
                default=secrets.token_hex,
                help_text="Unique external ID required in the role's trust policy, prevents the confused deputy problem.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="cloudaccount",
            name="role_arn",
            field=models.CharField(
                blank=True,
                default="",
                help_text="ARN of the IAM Role the company created for CloudOps AI to assume.",
                max_length=255,
            ),
        ),
    ]
